### ISSUE TITLE
How does one type half sounds?

### ISSUE THREAD

**Issue by ArnavGautamGit** [srix55/sanskrit-kagapa-windows#1]
Half sounds are produced by "Halant". I have tried to find day and night, but there seems to be no halant key on this.
I cannot type half sounds and hence cannot type words similar to Dwitiya/द्वितीय where द and वि combine to form द्वि

द (half) + व + ि = द्वि

I am unable to type half द without the Halant key! If it is present, where is it?

**Comment by srix55** [comment]
You'll have to type it like this -
`d,f,v,i`
Refer the layout. For alternative letters, use right-alt & right-alt + shift. 
For example, for `ऊर्णनाभः`, you would type 
`rightAlt-rightShift-U, r, f, shift-n, shift-a, shift-b, shift-h`

Might look hard. But, it's intuitive once you type a few words. The layout is like this.
![image](https://github.com/srix55/sanskrit-kagapa-windows/assets/6329365/4a3900b7-3bf1-4043-a55f-f6f4eebc4bb4)
